export const projects = [
    {
        id: 1,
        image: "images/todoSS.jpg",
        name: "Todo App",
        desc: "A feature-rich todo application that lets you organize your day with ease. Create custom todo categories, add new tasks on the fly, and mark them as complete to keep your workflow clean. All data is persisted in LocalStorage so your todos are always there when you come back.",
        tech: ['ReactJS', 'TailwindCSS', 'LocalStorage'],
        github_link: 'https://github.com/prayushbogati/Todo-App-node',
    },
    {
        id: 2,
        image: "images/passMan.jpg",
        name: "Password Manager App",
        desc: "A secure and intuitive password manager that stores all your credentials in one place. Easily add new entries, edit existing ones, and delete passwords you no longer need. Built with a MongoDB backend to ensure your data is reliably stored and retrieved across sessions.",
        tech: ['ReactJS', 'ExpressJS', 'TailwindCSS', 'MongoDB'],
        github_link: 'https://github.com/prayushbogati/password-manager',
    },
    {
        id: 3,
        image: "images/keeper.jpg",
        name: "Keeper App",
        desc: "A clean and minimal note-keeping app inspired by Google Keep. Jot down your thoughts, ideas, and reminders instantly, and remove them once they're no longer needed. Backed by a RESTful Express API and MongoDB so your notes sync and persist seamlessly.",
        tech: ['ReactJS', 'ExpressJS', 'TailwindCSS', 'MongoDB'],
        github_link: 'https://github.com/prayushbogati/Keeper-App',
    },
    {
        id: 4,
        image: "images/blog.jpg",
        name: "Blog App",
        desc: "A full-stack blogging platform where you can write, publish, and manage blog posts with ease. Compose rich new posts, browse existing entries, and keep your content organized. Powered by an Express backend and MongoDB for reliable content storage and retrieval.",
        tech: ['ReactJS', 'ExpressJS', 'TailwindCSS', 'MongoDB'],
        github_link: 'https://github.com/prayushbogati/MERN-blog-crud',
    },
    {
        id: 5,
        image: "images/vaxocare.jpeg",
        name: "VAXOCARE",
        desc: "A comprehensive Child Vaccination Management System designed to help parents and healthcare providers track and manage vaccination schedules. Features real-time notifications via Socket.IO to alert guardians of upcoming doses, with a full MERN stack backend ensuring secure and accurate record management.",
        tech: ['ReactJS', 'ExpressJS', 'TailwindCSS', 'MongoDB', 'SocketIO'],
        github_link: 'https://github.com/prayushbogati/vaxocare',
    },
];